package ru.sbercourse.cinema.ticketoffice.model;

public enum Country {
    UNITED_STATES("Соединенные Штаты"),
    CHINA("Китай"),
    INDIA("Индия"),
    JAPAN("Япония"),
    GERMANY("Германия"),
    UNITED_KINGDOM("Великобритания"),
    FRANCE("Франция"),
    ITALY("Италия"),
    CANADA("Канада"),
    SOUTH_KOREA("Южная Корея"),
    RUSSIA("Россия"),
    BRAZIL("Бразилия"),
    AUSTRALIA("Австралия"),
    SPAIN("Испания"),
    MEXICO("Мексика"),
    INDONESIA("Индонезия"),
    NETHERLANDS("Нидерланды"),
    SAUDI_ARABIA("Саудовская Аравия"),
    TURKEY("Турция"),
    SWITZERLAND("Швейцария"),
    ARGENTINA("Аргентина"),
    SWEDEN("Швеция"),
    POLAND("Польша"),
    BELGIUM("Бельгия"),
    NORWAY("Норвегия"),
    AUSTRIA("Австрия"),
    IRELAND("Ирландия"),
    SINGAPORE("Сингапур"),
    DENMARK("Дания"),
    MALAYSIA("Малайзия"),
    THAILAND("Таиланд"),
    ISRAEL("Израиль"),
    SOUTH_AFRICA("Южная Африка"),
    PHILIPPINES("Филиппины"),
    COLOMBIA("Колумбия"),
    CHILE("Чили"),
    FINLAND("Финляндия"),
    CZECH_REPUBLIC("Чехия"),
    PORTUGAL("Португалия"),
    ROMANIA("Румыния"),
    HUNGARY("Венгрия"),
    NEW_ZEALAND("Новая Зеландия"),
    GREECE("Греция"),
    VIETNAM("Вьетнам"),
    PERU("Перу"),
    EGYPT("Египет"),
    BANGLADESH("Бангладеш"),
    PAKISTAN("Пакистан"),
    NIGERIA("Нигерия"),
    UKRAINE("Украина"),
    VENEZUELA("Венесуэла"),
    KAZAKHSTAN("Казахстан"),
    ALGERIA("Алжир"),
    MOROCCO("Марокко"),
    SLOVAKIA("Словакия"),
    CROATIA("Хорватия"),
    BULGARIA("Болгария"),
    SLOVENIA("Словения"),
    LITHUANIA("Литва"),
    LATVIA("Латвия"),
    ESTONIA("Эстония"),
    SERBIA("Сербия"),
    BOSNIA_AND_HERZEGOVINA("Босния и Герцеговина"),
    NORTH_MACEDONIA("Северная Македония"),
    GEORGIA("Грузия"),
    ARMENIA("Армения"),
    AZERBAIJAN("Азербайджан"),
    BELARUS("Беларусь"),
    UZBEKISTAN("Узбекистан"),
    TURKMENISTAN("Туркменистан"),
    KYRGYZSTAN("Киргизия"),
    TAJIKISTAN("Таджикистан"),
    MONGOLIA("Монголия"),
    CAMBODIA("Камбоджа"),
    LAOS("Лаос"),
    SRI_LANKA("Шри-Ланка"),
    MYANMAR("Мьянма"),
    JORDAN("Иордания"),
    LEBANON("Ливан"),
    TUNISIA("Тунис"),
    LIBYA("Ливия"),
    IRAQ("Ирак"),
    IRAN("Иран"),
    KUWAIT("Кувейт"),
    QATAR("Катар"),
    UNITED_ARAB_EMIRATES("ОАЭ"),
    OMAN("Оман"),
    YEMEN("Йемен"),
    AFGHANISTAN("Афганистан"),
    MALDIVES("Мальдивы"),
    NEPAL("Непал"),
    BHUTAN("Бутан"),
    ICELAND("Исландия"),
    LUXEMBOURG("Люксембург"),
    MONACO("Монако"),
    ANDORRA("Андорра"),
    SAN_MARINO("Сан-Марино"),
    MALTA("Мальта");

    private final String text;

    Country(String text) {
        this.text = text;
    }

    public String getText() {
        return text;
    }
}
